name: Run Flask Unit & Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      FLASK_ENV: testing
      FLASK_APP: run.py
      DATABASE_URL: sqlite:///test_workouts.db  # used by your app config

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Delete old test DB
        run: rm -f test_workouts.db

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Install frontend & Cypress dependencies
        run: |
          npm install
          npx cypress install

      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Start Flask app
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &
          echo "Waiting for Flask to start..."
          sleep 5
          until curl --silent --fail http://localhost:5000; do
            echo "Waiting for app..."
            sleep 2
          done
          sleep 5
          echo "App is running"

      - name: Reset database
        run: |
          curl http://localhost:5000/reset_db

      - name: Run unit tests
        run: pytest app/test/unit

      - name: Run Cypress tests
        run: npx cypress run
