name: Run Flask Unit & Cypress Tests

on:
  push:
    branches:
      - main  # Change to your branch name if different

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      FLASK_CONFIG: app.config.TestingConfig
      DATABASE_URL: postgresql://testuser:testpass@localhost:5432/testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          pytest app/test/unit

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Cypress dependencies
        run: |
          npm install --prefix cypress

      - name: Start Flask app in background
        run: |
          export FLASK_APP=app
          flask db upgrade
          nohup flask run --host=127.0.0.1 --port=5000 &
          sleep 5

      - name: Run Cypress tests
        run: |
          npx cypress run
