name: Run Flask & Cypress Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      FLASK_ENV: testing
      DATABASE_URL: sqlite:///test_workouts.db
      CYPRESS_baseUrl: http://localhost:5000

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Flask-Session

      - name: Cache Hugging Face Transformers models
        uses: actions/cache@v3
        with:
          path: ~/.cache/torch/sentence_transformers
          key: hf-model-cache-all-MiniLM-L6-v2-${{ runner.os }}-${{ hashFiles('path/to/your/code') }}
          restore-keys: |
            hf-model-cache-all-MiniLM-L6-v2-${{ runner.os }}-
            hf-model-cache-all-MiniLM-L6-v2-

      - name: Preload SentenceTransformer model
        run: |
          python -c "from sentence_transformers import SentenceTransformer; SentenceTransformer('all-MiniLM-L6-v2')"


      - name: Set up database and seed user
        run: |
          python -c "from app import create_app, db; app = create_app(); app.app_context().push(); db.create_all()"
          python -c "from app import create_app, db; from app.models import User; app = create_app(); app.app_context().push(); db.session.add(User(email='test@example.com', password='password')); db.session.commit()"

      - name: Start Flask app
        run: |
          echo "Starting Flask app..."
          FLASK_APP=run.py FLASK_ENV=testing python -u -m flask run --no-reload --without-threads --host=0.0.0.0 --port=5000 &
          sleep 5

      - name: Install Node.js and Cypress
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install
        working-directory: ./cypress

      - name: Run Cypress tests
        run: npx cypress run
        working-directory: ./cypress
